### ISSUE TITLE
error in alsa-capabilties: UO_EP_LABELS[${alsa_if_uac_ep}]: unbound variable

### ISSUE THREAD

**Issue by hurra** [ronalde/mpd-configure#11]
pi@raspberrypi ~ $ export scriptname="alsa-capabilities"
pi@raspberrypi ~ $ export url="https://raw.githubusercontent.com/ronalde/mpd-configure/master/${scriptname}"
pi@raspberrypi ~ $ wget -q "${url}" || curl -s -k -o "${scriptname}" "${url}"
pi@raspberrypi ~ $ sudo bash alsa-capabilities 
alsa-capabilities: line 191: UO_EP_LABELS[${alsa_if_uac_ep}]: unbound variable

**Comment by hurra** [comment]
pi@raspberrypi ~ $ cat /etc/debian_version 
7.8

**Comment by hurra** [comment]
pi@raspberrypi ~ $ bash --version
GNU bash, version 4.2.37(1)-release (arm-unknown-linux-gnueabihf)

**Comment by ronalde** [comment]
Dear hurra, 

It seames you've hit a rather structural bug in the script with regard to dealing with empty variables in unexpected situations. 

Could you please add the output of the following command on your raspberrypi to this bug:
`LANG=C aplay -l 2>&1`

Thanks,
Ronald

**Comment by ronalde** [comment]
Hurra,

As an alternative you might try the python version I'm developing (in the 'python' branch) in order to overcome my bash shortcomings. Although some features are not implemented yet (the limit and filter options), the basics should work.

```bash
export scriptname="alsa_capabilities.py"
export url="https://raw.githubusercontent.com/ronalde/mpd-configure/python/${scriptname}"
wget -q "${url}" || curl -s -k -o "${scriptname}" "${url}"
sudo python alsa_capabilities.py
```

If you do I would like to hear if it works and if python would be a viable option for your purpose?

Regards,
Ronald

**Comment by hurra** [comment]
python:

pi@raspberrypi ~ $ export scriptname="alsa_capabilities.py"
pi@raspberrypi ~ $ export url="https://raw.githubusercontent.com/ronalde/mpd-configure/python/${scriptname}"
pi@raspberrypi ~ $ wget -q "${url}" || curl -s -k -o "${scriptname}" "${url}"
pi@raspberrypi ~ $ sudo python alsa_capabilities.py
* `USB Audio' output of sound device `USB Audio DAC' on host `raspberrypi'
  - hardware address  = hw:0,0
  - electrical        = Digital (USB) audio output interface
  - character device  = /dev/snd/pcmC0D0p (not in use)
  - monitor file      = /proc/asound/card0/pcm0p/sub0/hw_params (accessible, closed)
  - usb audio class   = 1: isochronous adaptive
  - sample formats    = S16_LE

Then the script seems to hang forever, i pressed ctrl-c to end it

^CTraceback (most recent call last):
  File "alsa_capabilities.py", line 389, in <module>
    main()
  File "alsa_capabilities.py", line 385, in main
    aif = class_alsa_interface(line)
  File "alsa_capabilities.py", line 80, in __init__
    self.sampleformats = self.get_sampleformats()
  File "alsa_capabilities.py", line 174, in get_sampleformats
    stdout_value, stderr_value = proc.communicate(b'bla')
  File "/usr/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1322, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1376, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt



When the device is in use, i get the following:
pi@raspberrypi ~ $ sudo python alsa_capabilities.py
Traceback (most recent call last):
  File "alsa_capabilities.py", line 389, in <module>
    main()
  File "alsa_capabilities.py", line 385, in main
    aif = class_alsa_interface(line)
  File "alsa_capabilities.py", line 80, in __init__
    self.sampleformats = self.get_sampleformats()
  File "alsa_capabilities.py", line 193, in get_sampleformats
    pname=self.inspect_chardev()
  File "alsa_capabilities.py", line 161, in inspect_chardev
    return result
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by hurra** [comment]
pi@raspberrypi ~ $ LANG=C aplay -l 2>&1
**** List of PLAYBACK Hardware Devices ****
card 0: DAC [USB Audio DAC], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by ronalde** [comment]
Thanks, will look in to it tomorrow

**Comment by ronalde** [comment]
The results so far: python has a long way to go, but the original bash script is fixable.

It needs a lot of improvement in handling errors though. I've implemented some improvements in  commit:567eda96150d866eccc3c9afc822dbf176dba8b2.  But dor a real robust script I need more time. It seems raspeberrypi differs more from my environments (intel pc with arch and debian) than I assumed.

So you might try the current version of the bash script in the master branch, using the original procedure for downloading and running the script. Or if you can, wait some time.

Regards,
Ronald

**Comment by ronalde** [comment]
Some more fixes, see commit ec0c5db6bc7bcfebc6d22a183b7f13bc0d2d15a5

**Comment by ronalde** [comment]
[Canistel wrote:](http://lacocina.nl/detect-alsa-output-capabilities#comment-790)

I get the exact same error message, just downloaded your script today. Here is my aplay -l:
```
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: USB [Scarlett 2i2 USB], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: PCH [HDA Intel PCH], device 0: CS4208 Analog [CS4208 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: PCH [HDA Intel PCH], device 1: CS4208 Digital [CS4208 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by ronalde** [comment]
@Canistel: I've made some alterations which I think should resolve this issue.

Could you pleas try to run the following (all one single line, followed by ENTER):
```
cd /tmp/ && bash <(wget -q -O - "https://raw.githubusercontent.com/ronalde/mpd-configure/nomapfile/alsa-capabilities")
```

Thanks,
Ronald

**Comment by ronalde** [comment]
The previous change didn't solve this. There was a problem in the regular expression which tries too extract the fixed strings ASYNC or ADAPTIVE from the stream file (it took me another DAC to find this problem). 

The latest change (commit:5f5c57863235bcd26ffe9239751e9bd33cc0ae8e) does solve this issue. I hope once and for all.
