### ISSUE TITLE
alsa-capabilities: fuser hangs on microcard root filesystem with raspberrypi

### ISSUE THREAD

**Issue by taudac** [ronalde/mpd-configure#12]
The scripts `alsa-capabilities` and `mpd-configure` hang at line `${CMD_FUSER} -v ${chardev_path} 2>&1`.

- Tested with: `bash -v alsa-capabilities`
- Tested on: Raspbarry Pi, kernel 4.3

**Comment by ronalde** [comment]
Could you try running it with the debug flag set and attach the output to this bug report, eg:
```
DEBUG=True bash -v alsa-capabilities
```

Regards,
Ronald

**Comment by taudac** [comment]
Here is the tail of the output:

	## if the script is not sourced by another script but run within its
	## own shell call function `return_alsa_interface'
	[[ "${BASH_SOURCE[0]:-}" != "${0}" ]] || return_alsa_interface "$@"
	DEBUG *** entering `return_alsa_interface' with arguments `'
	which aplay || command_not_found "aplay" "alsa-utils"
	which fuser || command_not_found "fuser" "psmisc"
	DEBUG *** entering `analyze_command_line' with arguments `'
	DEBUG *** entering `pulseaudio_evaluate_stopping' with arguments `'
	which pulseaudio
	DEBUG *** no pulseaudio command found in path.
	DEBUG *** entering `fetch_alsa_outputinterfaces' with arguments `'
	${CMD_APLAY} -l 2>&1
	${CMD_APLAY} -l
	DEBUG *** Inspecting interface: card 0: TauDACDM101 [TauDAC-DM101], device 0: TauDAC HiFi multicodec-0 []
	DEBUG ***                match: card 0: TauDACDM101 [TauDAC-DM101], device 0: TauDAC HiFi multicodec-0 []
	printf "errors: %s\n" "${errors[@]}"
	DEBUG *** errors: could not fetch interface label
	check_alsa_chardev "${alsa_if_chardev}"
	DEBUG *** entering `check_alsa_chardev' with arguments `/dev/snd/pcmC0D0p'
	DEBUG *** fetch_alsa_outputinterfaces: check_alsa_chardev returned no error: `/dev/snd/pcmC0D0p'
	get_locking_process "${alsa_if_chardev}"
	DEBUG *** entering `get_locking_process' with arguments `/dev/snd/pcmC0D0p'
	${CMD_FUSER} -v ${chardev_path} 2>&1

The execution hangs here.

**Comment by ronalde** [comment]
Could it be your /dev tree is on nfs (or another networked file system)?

**Comment by taudac** [comment]
Here is the output of `df -H`, does it help?

	Filesystem      Size  Used Avail Use% Mounted on
	/dev/root        16G  3.4G   12G  23% /
	devtmpfs        481M     0  481M   0% /dev
	tmpfs           486M     0  486M   0% /dev/shm
	tmpfs           486M  6.6M  479M   2% /run
	tmpfs           5.3M  4.1k  5.3M   1% /run/lock
	tmpfs           486M     0  486M   0% /sys/fs/cgroup
	/dev/mmcblk0p1   59M   26M   34M  43% /boot
	tmpfs            98M     0   98M   0% /run/user/1000

**Comment by ronalde** [comment]
Not really (only the /boot filesystem seems to be a local device). Could you please paste the output of the following commands:

```
grep root /proc/cmdline
```

```
readlink -f /dev/root
```

Thanks,
Ronald

**Comment by ronalde** [comment]
(FIY: the fuser command is known to 'hang' when used on a networked filesystem)

**Comment by taudac** [comment]
`grep root /proc/cmdline` returns:

    ... root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

`readlink -f /dev/root` returns:

    /dev/root

**Comment by ronalde** [comment]
Thanks. So /root is also local. 

Does running the command from the command line hang as well:
```
fuser -v /dev/snd/pcmC0D0p
```

**Comment by taudac** [comment]
Yes!

**Comment by ronalde** [comment]
Thanks. So I will have to replace fuser with something else. Please hold on for a couple of minutes.

**Comment by ronalde** [comment]
taudac, could you please try:
```
cd /tmp/ && bash <(wget -q -O - "https://raw.githubusercontent.com/ronalde/mpd-configure/fuser-replacement/alsa-capabilities")
```

**Comment by taudac** [comment]
Now it hangs here:

    ...
	## if the script is not sourced by another script but run within its
	## own shell call function `return_alsa_interface'
	[[ "${BASH_SOURCE[0]:-}" != "${0}" ]] || return_alsa_interface "$@"
	DEBUG *** entering `return_alsa_interface' with arguments `'
	which aplay || command_not_found "aplay" "alsa-utils"
	DEBUG *** entering `analyze_command_line' with arguments `'
	DEBUG *** entering `pulseaudio_evaluate_stopping' with arguments `'
	which pulseaudio
	DEBUG *** no pulseaudio command found in path.
	DEBUG *** entering `fetch_alsa_outputinterfaces' with arguments `'
	${CMD_APLAY} -l 2>&1
	${CMD_APLAY} -l
	DEBUG *** Inspecting interface: card 0: TauDACDM101 [TauDAC-DM101], device 0: TauDAC HiFi multicodec-0 []
	DEBUG ***                match: card 0: TauDACDM101 [TauDAC-DM101], device 0: TauDAC HiFi multicodec-0 []
	printf "errors: %s\n" "${errors[@]}"
	DEBUG *** errors: could not fetch interface label
	check_alsa_chardev "${alsa_if_chardev}"
	DEBUG *** entering `check_alsa_chardev' with arguments `/dev/snd/pcmC0D0p'
	DEBUG *** fetch_alsa_outputinterfaces: check_alsa_chardev returned no error: `/dev/snd/pcmC0D0p'
	get_locking_process "${alsa_if_chardev}"
	DEBUG *** entering `get_locking_process' with arguments `/dev/snd/pcmC0D0p'
	DEBUG *** get_locking_process: `/dev/snd/pcmC0D0p' is a chardev
	find /proc -type l -printf "%p -> %l/\n" 2>/dev/null | grep -m 1 "${chardev_path}" | grep task

**Comment by taudac** [comment]
`find /proc -type l` hangs here:
	...
	/proc/891/fd/7
	/proc/891/fd/8
	/proc/891/fd/9
	/proc/891/fd/10
	/proc/891/fd/11
	/proc/891/fd/12

**Comment by ronalde** [comment]
taudac, I've created a new testing branch which limits the execution time of fuser to 0.01s. 

Could you please try:
```
cd /tmp/ && bash <(wget -q -O - "https://raw.githubusercontent.com/ronalde/mpd-configure/fuser-timeout/alsa-capabilities")
```

**Comment by taudac** [comment]
Now it stops here:

	## if the script is not sourced by another script but run within its
	## own shell call function `return_alsa_interface'
	[[ "${BASH_SOURCE[0]:-}" != "${0}" ]] || return_alsa_interface "$@"
	DEBUG *** entering `return_alsa_interface' with arguments `'
	which aplay || command_not_found "aplay" "alsa-utils"
	which fuser || command_not_found "fuser" "psmisc"
	DEBUG *** entering `analyze_command_line' with arguments `'
	DEBUG *** entering `pulseaudio_evaluate_stopping' with arguments `'
	which pulseaudio
	DEBUG *** no pulseaudio command found in path.
	DEBUG *** entering `fetch_alsa_outputinterfaces' with arguments `'
	${CMD_APLAY} -l 2>&1
	${CMD_APLAY} -l
	DEBUG *** Inspecting interface: card 0: TauDACDM101 [TauDAC-DM101], device 0: TauDAC HiFi multicodec-0 []
	DEBUG ***                match: card 0: TauDACDM101 [TauDAC-DM101], device 0: TauDAC HiFi multicodec-0 []
	printf "errors: %s\n" "${errors[@]}"
	DEBUG *** errors: could not fetch interface label
	check_alsa_chardev "${alsa_if_chardev}"
	DEBUG *** entering `check_alsa_chardev' with arguments `/dev/snd/pcmC0D0p'
	DEBUG *** fetch_alsa_outputinterfaces: check_alsa_chardev returned no error: `/dev/snd/pcmC0D0p'
	get_locking_process "${alsa_if_chardev}"
	DEBUG *** entering `get_locking_process' with arguments `/dev/snd/pcmC0D0p'
	DEBUG *** get_locking_process: `/dev/snd/pcmC0D0p' is a chardev
	 cmdpid=$BASHPID; (sleep 0.01s; kill -9 $cmdpid 2>/dev/null ) & ${CMD_FUSER} ${chardev_path} 2>/dev/null

**Comment by taudac** [comment]
I have pulled the latest rpi-4.3 source and rebuild the kernel. Now, I can not reproduce the issue any more. 

Sorry for the noise!

And many thanks for your time and effort!

**Comment by ronalde** [comment]
Thanks for the feedback,
Ronald
